### ISSUE TITLE
Issues with Alfresco Solr

### ISSUE THREAD

**Issue by tomasjkn** [Open-MBEE/EMS-Repo#1]
Hello,

I've been banging my head against the wall and pulling my hair out with the following problem:

I have EMS-Repo set up on Alfresco;
and MDK set up on MagicDraw.
The tests at the test-data/*.json work and correctly post to Alfresco (as described in EMS-Repo/Readme.md).

Now  I am trying to initialize top level structures for the sample project DocGen (coming with the MDK plugin) from MagicDraw/MDK side.

But when I try to create project structures from MagicDraw/MDK side, I get the following exception from deep in the guts of the Alfresco/Solr:
java.lang.NullPointerException
    at org.alfresco.repo.search.impl.lucene.SolrJSONResultSet.length(SolrJSONResultSet.java:316)
    at org.alfresco.repo.security.permissions.impl.acegi.FilteringResultSet.<init>(FilteringResultSet.java:52)
    at org.alfresco.repo.security.permissions.impl.acegi.ACLEntryAfterInvocationProvider.decideNew(ACLEntryAfterInvocationProvider.java:543)
    at org.alfresco.repo.security.permissions.impl.acegi.ACLEntryAfterInvocationProvider.decide(ACLEntryAfterInvocationProvider.java:530)
    at org.alfresco.repo.security.permissions.impl.acegi.ACLEntryAfterInvocationProvider.decide(ACLEntryAfterInvocationProvider.java:296)
    at net.sf.acegisecurity.afterinvocation.AfterInvocationProviderManager.decide(AfterInvocationProviderManager.java:107)
    at net.sf.acegisecurity.intercept.AbstractSecurityInterceptor.afterInvocation(AbstractSecurityInterceptor.java:333)
    at net.sf.acegisecurity.intercept.method.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:82)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.security.permissions.impl.ExceptionTranslatorMethodInterceptor.invoke(ExceptionTranslatorMethodInterceptor.java:46)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.alfresco.repo.audit.AuditMethodInterceptor.invoke(AuditMethodInterceptor.java:161)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
    at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
    at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
    at com.sun.proxy.$Proxy32.query(Unknown Source)
    at gov.nasa.jpl.view_repo.util.NodeUtil.luceneSearch(NodeUtil.java:126)
    at gov.nasa.jpl.view_repo.util.NodeUtil.luceneSearch(NodeUtil.java:113)
    at gov.nasa.jpl.view_repo.util.NodeUtil.findNodeRefsByType(NodeUtil.java:141)
    at gov.nasa.jpl.view_repo.util.NodeUtil.findNodeRefsByType(NodeUtil.java:172)
    at gov.nasa.jpl.view_repo.util.NodeUtil.findNodeRefByType(NodeUtil.java:156)
    at gov.nasa.jpl.view_repo.util.NodeUtil.findNodeRefByType(NodeUtil.java:148)
    at gov.nasa.jpl.view_repo.util.NodeUtil.findNodeRefById(NodeUtil.java:242)
    at gov.nasa.jpl.view_repo.webscripts.AbstractJavaWebScript.findScriptNodeById(AbstractJavaWebScript.java:212)
    at gov.nasa.jpl.view_repo.webscripts.ProjectPost.updateOrCreateProject(ProjectPost.java:182)
    at gov.nasa.jpl.view_repo.webscripts.ProjectPost.executeImpl(ProjectPost.java:88)
    at org.springframework.extensions.webscripts.DeclarativeWebScript.execute(DeclarativeWebScript.java:64)
    at org.alfresco.repo.web.scripts.RepositoryContainer$3.execute(RepositoryContainer.java:429)
    at org.alfresco.repo.transaction.RetryingTransactionHelper.doInTransaction(RetryingTransactionHelper.java:452)
    at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecute(RepositoryContainer.java:491)
    at org.alfresco.repo.web.scripts.RepositoryContainer.transactionedExecuteAs(RepositoryContainer.java:529)
    at org.alfresco.repo.web.scripts.RepositoryContainer.executeScript(RepositoryContainer.java:341)
    at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:378)
    at org.springframework.extensions.webscripts.AbstractRuntime.executeScript(AbstractRuntime.java:209)
    at org.springframework.extensions.webscripts.servlet.WebScriptServlet.service(WebScriptServlet.java:132)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:208)
    at net.bull.javamelody.MonitoringFilter.doFilter(MonitoringFilter.java:181)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.alfresco.web.app.servlet.GlobalLocalizationFilter.doFilter(GlobalLocalizationFilter.java:61)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1023)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
    at org.apache.tomcat.util.net.AprEndpoint$SocketProcessor.run(AprEndpoint.java:1852)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

I have narrowed it down from the MD side to the following post:
Method: POST
URL:  http://localhost:8080/alfresco/service/javawebscripts/sites/europa/projects/PROJECT-ID_5_
4_10_10_33_37_AM_73f784d2_12860399d62__5449_ako_ammos_jpl_nasa_gov_127_0_0_1?fix
=true
JSON: {"name":"DocGen"}

I cannot understand what is wrong here :(. It looks like some internal problem with the Solr. But I do not know how to fight it. Rebuilding Solr indexes does not help.

Any help would be appreciated.
Sincerely,
Tomas Juknevicius

**Comment by cinyoung** [comment]
Wait for a new version of EMS-repo, which will be posted in the next couple days.

**Comment by aftimg** [comment]
We will also be releasing an AMI preconfigured

**Comment by Enquier** [comment]
This issue should be fixed by disabling Solr (see project wiki) and 2.1 version released May 4th
